# Copyright (c) Aaron Gallagher <_@habnab.it>
# See COPYING for details.

from distutils.core import setup
import os
import subprocess


# try to pull the version from git, or fall back on a previously-saved version.
try:
    proc = subprocess.Popen(['git', 'describe', '--tags', '--long'],
                            stdout=subprocess.PIPE)
except OSError:
    raw_version = None
else:
    raw_version = proc.communicate()[0].strip()

# git failed if the string is empty
if not raw_version:
    if not os.path.exists('version.txt'):
        print "git-describe failed and version.txt isn't present."
        print "are you installing from a github tarball?"
        raise
    print "couldn't determine version from git; using version.txt"
    with open('version.txt', 'rb') as infile:
        raw_version = infile.read()
else:
    with open('version.txt', 'wb') as outfile:
        outfile.write(raw_version)


# parse the git-described verion into something usable.
tag_version, commits, sha = raw_version.rsplit('-', 2)
if commits == '0':
    version = tag_version
else:
    version = '%s.dev%s' % (tag_version, commits)


with open('txsocksx/_version.py', 'w') as outfile:
    outfile.write("""
# This file is automatically generated by setup.py.
__version__ = %r
__sha__ = %r
""" % (version, sha))


with open('README.rst', 'rb') as infile:
    long_description = infile.read()

setup(
    name='txsocksx',
    version=version,
    description='Twisted client endpoints for SOCKS{4,4a,5}',
    long_description=long_description,
    author='Aaron Gallagher',
    author_email='_@habnab.it',
    url='https://github.com/habnabit/txsocksx',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Framework :: Twisted',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: ISC License (ISCL)',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 2.6',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 2 :: Only',
        'Topic :: Internet',
    ],
    license='ISC',

    packages=['txsocksx', 'txsocksx.test'],
)
